#!/bin/bash
# Install Codex CLI for the worker user: pinned npm package, box config,
# the irreversible-guard hook, and the codex-mode provider switcher.
# Idempotent — re-running refreshes hooks/instructions/tool and leaves an
# existing config.toml and the provider keys alone.
#
# Guard posture on the box (2026-09-16): the Codex path runs the Codex-shaped
# irreversible-guard only. Read-guard is deliberately NOT installed here — the
# box frees read/size limits so the agent can work, and the one barrier kept is
# the block on actions that cannot be undone (recursive force deletes, disk
# writes, force-pushes, history rewrites, publishes) plus the class-2 blocks
# that stop the agent from disabling the guard itself. A Claude-shaped hook
# under ~/.codex matches no Codex tool name and is silently inert, which is why
# the installed file is config/codex-irreversible-guard.mjs.
#
#   sudo CODEX_VERSION=0.154.0 bash scripts/install-codex.sh [person]
#
# Provider keys never come through this script or the repo: transfer the
# codex-mode registry + the active key from the daily driver (RUNBOOK §7.11),
# or add a provider on the box with `codex-mode add`.
#
# The two MCP API keys are personal: export EXA_API_KEY / CONTEXT7_API_KEY
# when running the script and the placeholders in config.toml are filled at
# first install; otherwise fill them in by hand afterwards.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PERSON_USER="${1:-${SUDO_USER:-person}}"
PERSON_HOME="$(getent passwd "${PERSON_USER}" | cut -d: -f6)"
if [[ -z "${PERSON_HOME}" ]]; then
  echo "no home for ${PERSON_USER}" >&2
  exit 1
fi

CODEX_VERSION="${CODEX_VERSION:-0.154.0}"

command -v node >/dev/null 2>&1 || { echo "node not found — run bootstrap first" >&2; exit 1; }
npm install -g "@openai/codex@${CODEX_VERSION}"

as_user() { runuser -u "${PERSON_USER}" -- "$@"; }
install_u() { install -o "${PERSON_USER}" -g "${PERSON_USER}" "$@"; }

install -d -m 0700 -o "${PERSON_USER}" -g "${PERSON_USER}" \
  "${PERSON_HOME}/.codex/hooks" "${PERSON_HOME}/.codex/modes" "${PERSON_HOME}/.local/bin"
# modes/keys in a second pass: install -d creates missing parents as root:root.
install -d -m 0700 -o "${PERSON_USER}" -g "${PERSON_USER}" "${PERSON_HOME}/.codex/modes/keys"
chmod 0700 "${PERSON_HOME}/.codex"

# config.toml: first install only. The provider block is managed by
# codex-mode and the MCP keys are substituted from the environment here
# because they are never committed.
if [[ ! -f "${PERSON_HOME}/.codex/config.toml" ]]; then
  cfg_tmp="$(mktemp)"
  cp "${REPO_DIR}/config/spectre-codex-config.toml" "${cfg_tmp}"
  if grep -q '<exa-api-key>\|<context7-api-key>' "${cfg_tmp}"; then
    if [[ -n "${EXA_API_KEY:-}" && -n "${CONTEXT7_API_KEY:-}" ]]; then
      python3 - "${cfg_tmp}" "${EXA_API_KEY}" "${CONTEXT7_API_KEY}" <<'PYEOF'
import sys
path, exa, context7 = sys.argv[1:4]
text = open(path, encoding="utf-8").read()
text = text.replace("<exa-api-key>", exa).replace("<context7-api-key>", context7)
open(path, "w", encoding="utf-8").write(text)
PYEOF
    else
      echo "note: EXA_API_KEY / CONTEXT7_API_KEY not set — MCP key placeholders left in config.toml" >&2
    fi
  fi
  install_u -m 0600 "${cfg_tmp}" "${PERSON_HOME}/.codex/config.toml"
  rm -f "${cfg_tmp}"
else
  echo "keeping existing ${PERSON_HOME}/.codex/config.toml"
fi

install_u -m 0644 "${REPO_DIR}/config/codex-instructions.md" \
  "${PERSON_HOME}/.codex/instructions.md"
install_u -m 0644 "${REPO_DIR}/config/codex-global-AGENTS.md" \
  "${PERSON_HOME}/.codex/AGENTS.md"
install_u -m 0644 "${REPO_DIR}/config/codex-irreversible-guard.mjs" \
  "${PERSON_HOME}/.codex/hooks/irreversible-guard.mjs"
# Read-guard is intentionally not installed on the box (see header). Remove a
# stale copy from an older install so no unused hook file lingers.
if [[ -f "${PERSON_HOME}/.codex/hooks/read-guard.mjs" ]]; then
  rm -f "${PERSON_HOME}/.codex/hooks/read-guard.mjs"
fi
install_u -m 0755 "${REPO_DIR}/scripts/codex-mode" \
  "${PERSON_HOME}/.local/bin/codex-mode"

# Same env.sh + ~/.bashrc wiring codex-mode's write_env_sh() creates, so a
# fresh box has the key exported before the first `codex-mode api` run.
env_sh="${PERSON_HOME}/.codex/modes/env.sh"
cat >"${env_sh}" <<EOF
# Generated by codex-mode; sourced from ~/.bashrc
export CODEX_THIRDPARTY_API_KEY="\$(cat "${PERSON_HOME}/.codex/modes/keys/current")"
EOF
chown "${PERSON_USER}:${PERSON_USER}" "${env_sh}"
chmod 600 "${env_sh}"
if ! grep -qsF ". \"${env_sh}\"" "${PERSON_HOME}/.bashrc" 2>/dev/null; then
  printf '\n# Codex third-party API key (managed by codex-mode)\n[ -f "%s" ] && . "%s"\n' \
    "${env_sh}" "${env_sh}" >>"${PERSON_HOME}/.bashrc"
  chown "${PERSON_USER}:${PERSON_USER}" "${PERSON_HOME}/.bashrc"
fi

as_user codex --version
echo "codex installed. Provider keys are not part of this script — see RUNBOOK §7.11."

# Agent guidance. Codex reads ~/.codex/AGENTS.md, which this script writes from
# config/codex-global-AGENTS.md (the "Session handoff" section lives there).
# Claude on the box learns tools the way obscura/devcodex do: a managed block
# in ~/.claude/CLAUDE.md. Append-only and idempotent — an existing block is
# left alone so local edits survive a re-run.
claude_md="${PERSON_HOME}/.claude/CLAUDE.md"
if [[ -f "${claude_md}" ]] && ! grep -qF 'codex-handoff:begin' "${claude_md}"; then
  cat >>"${claude_md}" <<'EOF'

<!-- codex-handoff:begin (managed by scripts/install-codex.sh) -->
## Session handoff

`codex-handoff` moves a Codex CLI session between this box and the daily
driver: `codex-handoff push` (from the project directory) hands the newest
session for that directory over, `codex-handoff pull` brings one back, and
`codex-handoff list` / `status` show what is where. The receiver resumes with
`codex resume <uuid>`. Handoffs are additive — an identical session on the peer
is a no-op, a differing one is refused unless `--replace` is given (which backs
the peer's copy up first), and nothing is ever deleted. See RUNBOOK §7.15.

Sessions the user asks to migrate or create must be **visible and controllable
in Orca**: bring them up as an Orca-managed terminal in the project's worktree
(`orca-ide terminal create --worktree path:<dir> --title <t> --command <cmd>`),
never a bare tmux session or an invisible background process — the operator
checks and controls work remotely through the Orca ADE client. A worktree may
hold several live terminals (a handoff session beside the qoder worker); Slack
`resume` then dispatches only through the worker's `terminal` pin in
`config/qoder-workers.json`, so pin the worker terminal when a second one
appears.
<!-- codex-handoff:end -->
EOF
  chown "${PERSON_USER}:${PERSON_USER}" "${claude_md}"
  echo "agent note appended to ${claude_md}"
fi
